version: "3.0"

services:
  empyrion:
    image: antimodes201/empyrion-server:latest
    volumes:
      - "./common:/home/steamuser/common"
    network_mode: "bridge"
    ports:
      - 30000-30004:30000-30004
      - 30000-30004:30000-30004/udp
    environment:
      - INSTANCE_NAME=t3stn3t
    #entrypoint: 
    #  - "tail"
    #  - "-f"
    #  - "/dev/null"